name: e2e
on:
  pull_request:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - uses: amondnet/vercel-action@v20
        id: deploy-vercel-staging
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npx playwright install
      - name: Run E2E test
        run: yarn test:e2e
        env:
          BASE_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
