name: test Next.js
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: microsoft/playwright-github-action@v1
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn
      - name: Check lint
        run: yarn lint
      - name: Check type
        run: yarn typecheck
      - name: Run test
        run: yarn test:ci
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.0.6
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: abekoh
          vercel_project_id: blog-next
      - name: Run E2E test
        run: BASE_URL="https://${{ steps.vercel_preview_url.outputs.preview_url }}" yarn test:e2e
